### ISSUE TITLE
Double season 8 in How I met your mother tsvr file

### ISSUE THREAD

**Issue by Ostefanini** [ronanboiteau/TV-Show-Randomizer#1]

**Comment by Ostefanini** [comment]
It seems like your tsvr file has some season 8 in duplicate.

**Comment by ronanboiteau** [comment]
Thanks for reporting this! Solved by [this commit](https://github.com/ronanboiteau/TV-Show-Randomizer/commit/2ef2c91f7cf0bc7943257961b84ecc0b40c5aa35).
